
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int END_BLOCK = 13;
  public static final int STRING_LITERAL = 20;
  public static final int CHAR = 33;
  public static final int OUTPUT = 56;
  public static final int END_LOOP = 47;
  public static final int COMMENT = 16;
  public static final int INPUT = 55;
  public static final int NEGA = 30;
  public static final int LOWER = 23;
  public static final int INT = 31;
  public static final int ARRAY = 36;
  public static final int FOR = 43;
  public static final int LESS = 25;
  public static final int PARAM = 18;
  public static final int PARENTS = 57;
  public static final int CHARSTR = 65;
  public static final int AND = 28;
  public static final int GREATHER = 22;
  public static final int OR = 29;
  public static final int BOOL = 34;
  public static final int DIV = 8;
  public static final int DECIDE_OF = 44;
  public static final int LOOP = 46;
  public static final int MAIN = 64;
  public static final int PARENTC = 58;
  public static final int END_DECIDE = 45;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int RETURN = 54;
  public static final int TRUE = 40;
  public static final int error = 1;
  public static final int SQUARES = 59;
  public static final int COMA = 19;
  public static final int MENOS = 4;
  public static final int GLOBAL = 37;
  public static final int BREAK = 53;
  public static final int EQ = 21;
  public static final int DMENOS = 5;
  public static final int INIT_BLOCK = 12;
  public static final int POTENCIA = 10;
  public static final int ARROW = 63;
  public static final int SQUAREC = 60;
  public static final int ELSE = 42;
  public static final int COMPARA = 26;
  public static final int FUNC = 17;
  public static final int TO = 50;
  public static final int UKRA = 61;
  public static final int DOLLAR = 66;
  public static final int LET = 38;
  public static final int FLOAT = 32;
  public static final int MULTI = 7;
  public static final int EXIT_WHEN = 48;
  public static final int RUSS = 62;
  public static final int STRING = 35;
  public static final int END_COMMENT = 15;
  public static final int DIFF = 27;
  public static final int DOWNTO = 51;
  public static final int FALSE = 41;
  public static final int INIT_COMMENT = 14;
  public static final int DMAS = 6;
  public static final int FLOAT_DIV = 9;
  public static final int DO = 52;
  public static final int MORE = 24;
  public static final int STEP = 49;
  public static final int INT_LITERAL = 11;
  public static final int MAS = 3;
  public static final int IDENTIFIER = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "MAS",
  "MENOS",
  "DMENOS",
  "DMAS",
  "MULTI",
  "DIV",
  "FLOAT_DIV",
  "POTENCIA",
  "INT_LITERAL",
  "INIT_BLOCK",
  "END_BLOCK",
  "INIT_COMMENT",
  "END_COMMENT",
  "COMMENT",
  "FUNC",
  "PARAM",
  "COMA",
  "STRING_LITERAL",
  "EQ",
  "GREATHER",
  "LOWER",
  "MORE",
  "LESS",
  "COMPARA",
  "DIFF",
  "AND",
  "OR",
  "NEGA",
  "INT",
  "FLOAT",
  "CHAR",
  "BOOL",
  "STRING",
  "ARRAY",
  "GLOBAL",
  "LET",
  "DOT",
  "TRUE",
  "FALSE",
  "ELSE",
  "FOR",
  "DECIDE_OF",
  "END_DECIDE",
  "LOOP",
  "END_LOOP",
  "EXIT_WHEN",
  "STEP",
  "TO",
  "DOWNTO",
  "DO",
  "BREAK",
  "RETURN",
  "INPUT",
  "OUTPUT",
  "PARENTS",
  "PARENTC",
  "SQUARES",
  "SQUAREC",
  "UKRA",
  "RUSS",
  "ARROW",
  "MAIN",
  "CHARSTR",
  "DOLLAR"
  };
}

